### ISSUE TITLE
What does the icon represent?

### ISSUE THREAD

**Issue by Foggalong** [fruho/fruhoapp#4]
Hi, I'm part of a team which makes icon themes for Linux and we've had a request to do one for fruhoapp. Problem is we can't make [head nor tail](https://github.com/numixproject/circle-core/pull/3369#issuecomment-239648983) of what the original icon is supposed to be. I'm thinking possibly a tree but I really don't know.

**Comment by hypatia2** [comment]
Hi, originally there was no semantics in the icon but let's say it's a tree.
