### ISSUE TITLE
add indicator to ubuntu version

### ISSUE THREAD

**Issue by grrrrr** [fruho/fruhoapp#5]
Can it be possible to add an indicator applet to the Top menu bar (where network, sound, clock are). And if possible have it be able to indicate the state of vpn connection like the network connection applet gets a lock when on VPN.

This would be allowing Ubuntu users to easily see if they are connected or not

**Comment by baimafeima** [comment]
I greatly appreciate an icon for the indicator area. 
OS: Solus: https://solus-project.com/

**Comment by seckiss** [comment]
These are desktop/distro dependent. Requires a lot of testing. No resources at the moment

**Comment by grrrrr** [comment]
closing as securitykiss who were the developers closed company
