### ISSUE TITLE
Add a network lock

### ISSUE THREAD

**Issue by grrrrr** [fruho/fruhoapp#6]
I would like to suggest the option of adding a _network lock_ to Fruho.  The purpose of this would be to drop all traffic from the computer should the VPN disconnect accidentally.

I would envision this using the built in firewalls of the supported OSes

**Comment by fruho** [comment]
This might be done by removing the default route when VPN connects and restoring when disconnects. On the TODO list

**Comment by grrrrr** [comment]
closing as securitykiss who were the developers closed company
